platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: compiled_bits_transfer_dir
outputs:
params:
  MAKE_TEST_COMMAND: ""
  CONFIGURE_FLAGS: ""
  WITH_MIRRORS:
  TRANSFER_DIR: compiled_bits_transfer_dir
run:
  path: gpdb_src/concourse/scripts/ic_gpdb_ubuntu.bash
